default: &default
  adapter: postgresql
  pool: 5
  imeout: 5000

development:
  adapter: postgresql
  database: shop_development
  pool: 5
  username: youname
  password: yourpassword
test:
  adapter: postgresql
  encoding: unicode
  database: shop_test
  pool: 5
  username: yourname
  password: yourpassword
