default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: sportshop_development
  pool: 5
  username: dartnyan
  password: kurt1245

test:
  adapter: postgresql
  encoding: unicode
  database: sportshop_test
  pool: 5
  username: dartnyan
  password: kurt1245
