default: &default
  adapter: postgresql
  pool: 5
  imeout: 5000

development:
  adapter: postgresql
  database: shop_development
  pool: 5
  username: dartnyan
  password: kurt1245
test:
  adapter: postgresql
  encoding: unicode
  database: shop_test
  pool: 5
  username: dartnyan
  password: kurt1245
