development:
  adapter: postgresql
  encoding: unicode
  database: shop_development
  pool: 5
  username: shop
  password: <%= ENV['SHOP_DATABASE_PASSWORD'] %>
test:
  adapter: postgresql
  encoding: unicode
  database: shop_test
  pool: 5
  username: shop
  password: <%= ENV['SHOP_DATABASE_PASSWORD'] %>
