development:
  adapter: postgresql
  encoding: unicode
  database: shop_development
  pool: 5
  username: shop
  password: 354293sas
test:
  adapter: postgresql
  encoding: unicode
  database: shop_test
  pool: 5
  username: shop
  password: 354293sas
